-------------------------------------------------------------------------------
Test set: trilha.back.financysdesafio06.FinancysDesafio06ApplicationTests
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.655 s <<< FAILURE! - in trilha.back.financysdesafio06.FinancysDesafio06ApplicationTests
contextLoads  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: trilha.back.financysdesafio06.entities.Entry.category in trilha.back.financysdesafio06.entities.Category.entries
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: trilha.back.financysdesafio06.entities.Entry.category in trilha.back.financysdesafio06.entities.Category.entries

